# This file is a template, and might need editing before it works on your project.
# This template has been DEPRECATED. Consider using Auto DevOps instead:
# https://docs.gitlab.com/ee/topics/autodevops

# Explanation on the scripts:
# https://gitlab.com/gitlab-examples/kubernetes-deploy/blob/master/README.md
image: registry.gitlab.com/gitlab-examples/kubernetes-deploy

variables:
  # Application deployment domain
  KUBE_DOMAIN: i2p.online

stages:
  - build
  - test
  - review
  - staging
  - production
  - cleanup
  - canary
  - chatops
  
  
hello-world:
  stage: chatops
  only: [chat]
  script:
    - echo "Hello World."

build:
  stage: build
  script:
    - command build
  only:
    - branches
    
    
canary:
  stage: canary
  script:
    - command canary
  environment:
    name: production
    url: http://$CI_PROJECT_PATH_SLUG.$KUBE_DOMAIN
  when: manual
  only:
    - master


production:
  stage: production
  script:
    - command deploy
  environment:
    name: production
    url: http://$CI_PROJECT_PATH_SLUG.$KUBE_DOMAIN
  when: manual
  only:
    - master

staging:
  stage: staging
  script:
    - command deploy
  environment:
    name: staging
    url: http://$CI_PROJECT_PATH_SLUG-staging.$KUBE_DOMAIN
  only:
    - master

review:
  stage: review
  script:
    - command deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master

sast:
  stage: test 
  script:
    - exit 0

rspec-mysql-unit-test:
  stage: test
  script:
    - exit 0

rspec-postgres-unit-test:
  stage: test
  script:
    - exit 0
    
coveralls-integration-test:
  stage: test
  script:
    - exit 0

simplecov-code-coverage:
  stage: test
  script:
    - exit 0

cucumber-mysql-acceptance-test:
  stage: test
  script:
    - exit 0

cucumber-postgres-acceptance-test:
  stage: test
  script:
    - exit 0

rubocop-static-analysis-test:
  stage: test
  script:
    - exit 0
